export const products = [
  {
    id: 1,
    name: "Lectura de Carta Natal",
    description:
      "Con una lectura de carta natal, podemos conocer nuestras energías, entender con qué talentos vinimos al mundo, que situaciones y escenarios de vida se llevaran el protagonismo durante este camino llamado vida.",
    price: 7000,
    category: "Astrologia",
    img: "https://res.cloudinary.com/dduwd2qy1/image/upload/v1682205854/Mi%20Universo%20Astral/astrologia/reporte-astrologico-carta-natal_r2wixy.jpg",
    stock: null,
    reqStock: false,
  },
  {
    id: 2,
    name: "Lectura de Revolución Solar",
    description:
      "Cada vez que cumplimos años, el Sol regresa al mismo punto donde se encontraba en el momento de nuestro nacimiento. A nivel cósmico un nuevo ciclo comienza. La revolución solar o retorno solar, es un estudio astrológico que te permite conocer cómo será la energía activa en los 12 meses siguientes a tu cumpleaños.Este hermoso reporte te permite descubrir que depara el siguiente ciclo solar, los desafíos por superar y las oportunidades para aprovechar.",
    price: 7000,
    category: "Astrologia",
    img: "https://res.cloudinary.com/dduwd2qy1/image/upload/v1682205860/Mi%20Universo%20Astral/astrologia/reportes-astrologia-revolucion-solar-carta-natal_3_vf5cp1.jpg",
    stock: null,
    reqStock: false,
  },
  {
    id: 3,
    name: "Pregunta específica",
    description: "Consiste en una pregunta especifica al Tarot.",
    price: 600,
    category: "Tarot",
    img: "https://res.cloudinary.com/dduwd2qy1/image/upload/v1682206164/Mi%20Universo%20Astral/Tarot/D_NQ_NP_2X_656658-MLA52145079783_102022-F_aedrss.webp",
    stock: null,
    reqStock: false,
  },
  {
    id: 4,
    name: "Concejo",
    description: "Aquí podes pedir un concejo para una situación en particular",
    price: 500,
    category: "Tarot",
    img: "https://res.cloudinary.com/dduwd2qy1/image/upload/v1682206030/Mi%20Universo%20Astral/Tarot/D_NQ_NP_866887-MLA48959040886_012022-O_b4mqrx.webp",
    stock: null,
    reqStock: false,
  },
  {
    id: 5,
    name: "Lectura Express",
    description:
      "Duración 15 minutos. Esta lectura incluye tres preguntas al Tarot.",
    price: 1500,
    category: "Tarot",
    img: "https://res.cloudinary.com/dduwd2qy1/image/upload/v1682206493/Mi%20Universo%20Astral/Tarot/LECTURAEXPRESS_1_xs7ear.png",
    stock: null,
    reqStock: false,
  },
  {
    id: 6,
    name: "Lectura Simple",
    description:
      "Duración 30 minutos. Aquí las tiradas se combinan de acuerdo a la necesidad del consultante. Esta lectura aporta información sobre las diferentes áreas de vida de la persona, otorgando información concisa y mayor claridad.",
    price: 2000,
    category: "Tarot",
    img: "https://res.cloudinary.com/dduwd2qy1/image/upload/v1682206108/Mi%20Universo%20Astral/Tarot/D_NQ_NP_2X_924949-MLA52144967310_102022-F_igjsxp.webp",
    stock: null,
    reqStock: false,
  },
  {
    id: 7,
    name: "Lectura Completa",
    description:
      "Duración 1 hora. . Aquí las tiradas se combinan de acuerdo a la necesidad del consultante. Esta lectura nos permite profundizar mucho mas en lo que sea que se consulte, aportando respuestas y claridad al consultante.",
    price: 4000,
    category: "Tarot",
    img: "https://res.cloudinary.com/dduwd2qy1/image/upload/v1682206090/Mi%20Universo%20Astral/Tarot/D_NQ_NP_2X_782032-MLA52144431737_102022-F_vtedx6.webp",
    stock: null,
    reqStock: false,
  },
  {
    id: 8,
    name: "Lectura Astrológica",
    description:
      "Duracion 1 hs -1,30 hs. Esta es una lectura anual que abarca doce areas de la vida del sujeto (generación de dinero, comunicación, hogar, familia, salud, pareja, profesión, etc). Aporta información concreta sobre cada área, mostrando la energía que estará disponible para los 12 meses siguientes.",
    price: 5000,
    category: "Tarot",
    img: "https://res.cloudinary.com/dduwd2qy1/image/upload/v1682206578/Mi%20Universo%20Astral/Tarot/images_rojdbf.jpg",
    stock: null,
    reqStock: false,
  },
  {
    id: 9,
    name: "Lectura Vincular",
    description:
      "Nos muestra que energías están disponibles en un vinculo, que piensa y siente ese otro, aportando respuestas sobre el futuro. ",
    price: 2000,
    category: "Tarot",
    img: "https://res.cloudinary.com/dduwd2qy1/image/upload/v1682206217/Mi%20Universo%20Astral/Tarot/D_NQ_NP_2X_780053-MLA52145048302_102022-F_exij8f.webp",
    stock: null,
    reqStock: false,
  },
  {
    id: 10,
    name: "Lectura de Proyecto Creativo",
    description:
      "Estas con ganas de arrancar un proyecto y no sabes si es potable? Lo arrancaste y te sentis frustrado o estancado? perdió vitalidad? Esta lectura esta enfocada en proyectos creativos, es excelente para poder ver la energía del mismo, donde están las trabas o dificultades, y que es lo que pide este proyecto. Aportará las respuestas necesarias para la toma de decisiones, junto con una mayor claridad sobre cuales son las variables que requieren poner foco, el futuro del mismo, etc.",
    price: 3000,
    category: "Tarot",
    img: "https://res.cloudinary.com/dduwd2qy1/image/upload/v1682206295/Mi%20Universo%20Astral/Tarot/li3htrxe0whoplshnjd8.jpg",
    stock: null,
    reqStock: false,
  },
  {
    id: 11,
    name: "Vela de abundancia",
    description:
      "Vaso de 9 cm de alto x 8 cm de diámetro.Sticker con frase o palabra inspiracional. Pabilo de algodón. Envase reutilizable. Vela de soja hecha a mano. Aroma Penoias",
    price: 1500,
    category: "Velas",
    img: "https://res.cloudinary.com/dduwd2qy1/image/upload/v1682204943/Mi%20Universo%20Astral/velas/img_0754.jpgw_1_jvk5fx.jpg",
    stock: 5,
    reqStock: true,
  },
  {
    id: 12,
    name: "Vela motivacional",
    description:
      "Vaso de 9 cm de alto x 8 cm de diámetro.Sticker con frase o palabra inspiracional. Pabilo de algodón. Envase reutilizable. Vela de soja hecha a mano. Aroma Café de Venecia",
    price: 2000,
    category: "Velas",
    img: "https://res.cloudinary.com/dduwd2qy1/image/upload/v1682204914/Mi%20Universo%20Astral/velas/img_0038.jpgw_1_r7vgzl.jpg",
    stock: 25,
    reqStock: true,
  },
  {
    id: 13,
    name: "Vela de pasión",
    description:
      "Vaso de 9 cm de alto x 8 cm de diámetro.Sticker con frase o palabra inspiracional. Pabilo de algodón. Envase reutilizable. Vela de soja hecha a mano. Aroma Café de Gardenia",
    price: 2000,
    category: "Velas",
    img: "https://res.cloudinary.com/dduwd2qy1/image/upload/v1682204851/Mi%20Universo%20Astral/velas/img_5304_2_ysswlir800n6wjbh_otvgwx.jpg",
    stock: 10,
    reqStock: true,
  },
  {
    id: 14,
    name: "Vela de amor",
    description:
      "Vaso de 9 cm de alto x 8 cm de diámetro.Sticker con frase o palabra inspiracional. Pabilo de algodón. Envase reutilizable. Vela de soja hecha a mano. Aroma Rosa y Sándalo",
    price: 1800,
    category: "Velas",
    img: "https://res.cloudinary.com/dduwd2qy1/image/upload/v1682204731/Mi%20Universo%20Astral/velas/img_0110.jpgw_1_y1utqf.jpg",
    stock: 12,
    reqStock: true,
  },
  {
    id: 15,
    name: "Vela de prosperidad",
    description:
      "Vaso de 9 cm de alto x 8 cm de diámetro.Sticker con frase o palabra inspiracional. Pabilo de algodón. Envase reutilizable. Vela de soja hecha a mano. Aroma Vervena.",
    price: 1900,
    category: "Velas",
    img: "https://res.cloudinary.com/dduwd2qy1/image/upload/v1682204711/Mi%20Universo%20Astral/velas/img_7367.jpgw_wuqeag.jpg",
    stock: 15,
    reqStock: true,
  },
  {
    id: 16,
    name: "Mate camionero estándar de aluminio liso",
    description:
      "Mate argentino «estándar» camionero con virola lisa de aluminio, el mismo es forrado en cuero y su interior es de calabaza. El mate puede ser adquirido en color negro y marron oscuro",
    price: 4900,
    category: "Mates",
    img: "https://res.cloudinary.com/dduwd2qy1/image/upload/v1682204159/Mi%20Universo%20Astral/mates/M2_qgznck.png",
    stock: 2,
    reqStock: true,
  },
  {
    id: 17,
    name: "Mate torpedo estándar de aluminio",
    description:
      "Mate argentino «estándar» torpedo con virola lisa de aluminio, el mismo es forrado en cuero y su interior es de calabaza. El mate puede ser adquirido en color negro y marron oscuro",
    price: 4200,
    category: "Mates",
    img: "https://res.cloudinary.com/dduwd2qy1/image/upload/v1682204250/Mi%20Universo%20Astral/mates/M4_j5l3lr.png",
    stock: 22,
    reqStock: true,
  },
  {
    id: 18,
    name: "Mate imperial cincelado",
    description:
      "Mate Camioneros con estilo Imperial forrados en cuero liso o Croco, con virola de alpaca labrada artesanalmente y apliques de Bronce",
    price: 13500,
    category: "Mates",
    img: "https://res.cloudinary.com/dduwd2qy1/image/upload/v1682204294/Mi%20Universo%20Astral/mates/Imperial_Cincelado_Bronce_2_zlyscv.jpg",
    stock: 19,
    reqStock: true,
  },
  {
    id: 19,
    name: "Mate camionero con base de alpaca",
    description:
      "Mate Camioneros con estilo Imperial forrados en cuero liso o Croco, con Base de Alpaca y Virola Cincelada.",
    price: 1200,
    category: "Mates",
    img: "https://res.cloudinary.com/dduwd2qy1/image/upload/v1682204328/Mi%20Universo%20Astral/mates/Mate_Camionero_BaseAlpaca_3_sm7hyj.jpg",
    stock: 8,
    reqStock: true,
  },
  {
    id: 20,
    name: "Mate imperial virola lisa",
    description:
      "Mate Camioneros con estilo Imperial forrados en cuero liso t Virosla Lisa.",
    price: 9000,
    category: "Mates",
    img: "https://res.cloudinary.com/dduwd2qy1/image/upload/v1682204374/Mi%20Universo%20Astral/mates/Imperial_Virola_Lisa_khyq98.jpg",
    stock: 15,
    reqStock: true,
  },
  {
    id: 21,
    name: "Mate Imperial cincelado con base",
    description:
      "Mate Camioneros con estilo Imperial forrados en cuero liso o Croco, con Virola Cincelada, apliques en bronce y base de alpaca.",
    price: 19500,
    category: "Mates",
    img: "https://res.cloudinary.com/dduwd2qy1/image/upload/v1682204377/Mi%20Universo%20Astral/mates/DSC07315_q3ae4h.jpg",
    stock: 4,
    reqStock: true,
  },
  {
    id: 22,
    name: "Mate Stanley 236 ml",
    description:
      "El mate Stanley mantiene la temperatura durante toda la cebada. Es práctico e higiénico. Si el producto es comprado en Argentina la garantía es de por vida; siempre y cuando cumpla con los requisitos solicitados. Alto: 11 cm – Ancho: 10 cm – Peso: 245 gramos – Capacidad: 0,236 litros – Acero inoxidable18/8: Sí – Apto lavavajillas: Sí – Libre de BPA: Sí",
    price: 21100,
    category: "Mates",
    img: "https://res.cloudinary.com/dduwd2qy1/image/upload/v1682204377/Mi%20Universo%20Astral/mates/DSC04622_zreias.jpg",
    stock: 10,
    reqStock: true,
  },
  {
    id: 23,
    name: "Mate Algarrobo 1 Color",
    description:
      "Mate Clásico de Algarrobo con forma variada, color madera combinado con el color a elección.",
    price: 10000,
    category: "Mates",
    img: "https://res.cloudinary.com/dduwd2qy1/image/upload/v1682204392/Mi%20Universo%20Astral/mates/Algarrobo_UnColor_1_yfcg4e.jpg",
    stock: 7,
    reqStock: true,
  },
];
